name = "marketing-team-workflow"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets" }

[[d1_databases]]
binding = "DB"
database_name = "marketing-team-workflow-db"
database_id = "a083422f-ff4a-4f58-8f21-8bb38d0b8a30"
migrations_dir = "drizzle/migrations"
