#!/usr/bin/env node
/**
 * Seed SQL generator for the local D1 database.
 *
 * Outputs INSERT statements for all seed data to stdout.
 * Pipe to wrangler to apply:
 *
 *   npx tsx scripts/seed-db.ts | wrangler d1 execute DB --local --file=-
 *
 * This is the single canonical seed source (run by `npm run db:seed`).
 * Existing rows are skipped (ON CONFLICT DO NOTHING) so this is safe to re-run.
 */

function now(): string {
  return new Date().toISOString();
}

function isoDate(daysFromNow: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().slice(0, 10);
}

function esc(s: string | null | undefined): string {
  if (s == null) return "NULL";
  return `'${s.replace(/'/g, "''")}'`;
}

const WS_ID = "ws_auralee_01";
const t = now();

const lines: string[] = [
  "-- Seed data generated by scripts/seed-db.ts",
  `-- Generated at: ${t}`,
  "",
  "-- Workspace",
  `INSERT INTO workspace (id, name, timezone, created_at) VALUES (${esc(WS_ID)}, '패션 마케팅팀', 'Asia/Seoul', ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  "",
  "-- Members",
  `INSERT INTO member (id, workspace_id, name, email, role) VALUES ('m_admin_01', ${esc(WS_ID)}, '윤지수', 'jisoo@auralee.co', 'admin') ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO member (id, workspace_id, name, email, role) VALUES ('m_02', ${esc(WS_ID)}, '박민준', 'minjun@auralee.co', 'member') ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO member (id, workspace_id, name, email, role) VALUES ('m_03', ${esc(WS_ID)}, '최수연', 'sooyeon@auralee.co', 'member') ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO member (id, workspace_id, name, email, role) VALUES ('m_04', ${esc(WS_ID)}, '이현우', 'hyunwoo@auralee.co', 'member') ON CONFLICT (id) DO NOTHING;`,
  "",
  "-- Brands",
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-01-${WS_ID}', ${esc(WS_ID)}, 'BEAKER 공통', '#0a84ff', 1, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-02-${WS_ID}', ${esc(WS_ID)}, 'BEAKER 바잉', '#5e5ce6', 2, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-03-${WS_ID}', ${esc(WS_ID)}, 'BEAKER OG', '#af52de', 3, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-04-${WS_ID}', ${esc(WS_ID)}, 'Maison Kitsune', '#ff375f', 4, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-05-${WS_ID}', ${esc(WS_ID)}, 'GANNI', '#ff9500', 5, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-06-${WS_ID}', ${esc(WS_ID)}, 'Studio Nicholson', '#30b0c7', 6, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-07-${WS_ID}', ${esc(WS_ID)}, 'Kaptain Sunshine', '#34c759', 7, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-08-${WS_ID}', ${esc(WS_ID)}, 'Margaret Howell', '#8e8e93', 8, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-09-${WS_ID}', ${esc(WS_ID)}, 'Auralee', '#bf5af2', 9, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO brand (id, workspace_id, name, color, sort_order, archived_at, created_at, updated_at) VALUES ('brand-default-10-${WS_ID}', ${esc(WS_ID)}, '공통', '#64d2ff', 10, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  "",
  "-- Projects",
  `INSERT INTO project (id, workspace_id, brand_id, name, one_line_objective, project_lead_id, target_start_date, target_end_date, archived_at, created_at, updated_at) VALUES ('proj_auralee_launch', ${esc(WS_ID)}, 'brand-default-09-${WS_ID}', '국내 론칭', '25 SS 컬렉션의 디지털·리테일 론칭 활동을 통합해 국내 론칭 인지도를 확보한다', 'm_admin_01', ${esc(isoDate(-30))}, ${esc(isoDate(14))}, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO project (id, workspace_id, brand_id, name, one_line_objective, project_lead_id, target_start_date, target_end_date, archived_at, created_at, updated_at) VALUES ('proj_cultural_collab', ${esc(WS_ID)}, 'brand-default-01-${WS_ID}', '한로로 협업', '뮤직 아이덴티티를 강화하고 아티스트 팬층과 새로운 접점을 만든다', 'm_02', ${esc(isoDate(-14))}, ${esc(isoDate(45))}, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO project (id, workspace_id, brand_id, name, one_line_objective, project_lead_id, target_start_date, target_end_date, archived_at, created_at, updated_at) VALUES ('proj_brand_strategy', ${esc(WS_ID)}, 'brand-default-04-${WS_ID}', '26FW 마케팅 플랜', '시즌 핵심 메시지를 국내 관점에서 재구성하고 데이터 기반 실행안을 경영진에 보고한다', 'm_admin_01', ${esc(isoDate(-7))}, ${esc(isoDate(7))}, NULL, ${esc(t)}, ${esc(t)}) ON CONFLICT (id) DO NOTHING;`,
  "",
  "-- Workstreams",
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws1_planning', 'proj_auralee_launch', '기획', 0) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws1_content', 'proj_auralee_launch', '콘텐츠 제작', 1) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws1_distribution', 'proj_auralee_launch', '매체·배포', 2) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws1_analytics', 'proj_auralee_launch', '분석·리포트', 3) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws2_partnerships', 'proj_cultural_collab', '협업·제휴', 0) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws2_creative', 'proj_cultural_collab', '크리에이티브', 1) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws2_events', 'proj_cultural_collab', '이벤트', 2) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws3_research', 'proj_brand_strategy', '리서치', 0) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws3_messaging', 'proj_brand_strategy', '메시지 프레임워크', 1) ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO workstream (id, project_id, name, "order") VALUES ('ws3_presentation', 'proj_brand_strategy', '발표 자료', 2) ON CONFLICT (id) DO NOTHING;`,
  "",
  "-- Tasks",
  taskInsert("task_p1_01", WS_ID, "proj_auralee_launch", "ws1_planning", "론칭 일정 및 마일스톤 체크리스트 확정", "25 SS 디지털·리테일 론칭 주요 일정을 유관 담당자와 합의한다.", "Done", "m_admin_01", "m_02", isoDate(-28), isoDate(-20), 3, "m_admin_01", t, t, isoDate(-20), null),
  taskInsert("task_p1_02", WS_ID, "proj_auralee_launch", "ws1_planning", "크리에이티브팀 캠페인 콘셉트 공유", "무드보드와 카피 방향을 크리에이티브 리드와 공유한다.", "Done", "m_03", "m_admin_01", isoDate(-25), isoDate(-18), 2, "m_admin_01", t, t, isoDate(-18), null),
  taskInsert("task_p1_03", WS_ID, "proj_auralee_launch", "ws1_content", "인스타그램 릴스 히어로 영상 제작", "25 SS 히어로 룩의 15초 세로형 편집본. 국문·영문 자막 필요.", "InProgress", "m_03", "m_admin_01", isoDate(-10), isoDate(3), 1, "m_admin_01", t, t, null, null),
  // Subtasks of task_p1_03 — demonstrate the board's inline subtask expand + rollup (one nested level)
  taskInsert("task_p1_03_a", WS_ID, "proj_auralee_launch", "ws1_content", "15초 편집본 스토리보드 작성", null, "Done", "m_03", null, isoDate(-10), isoDate(-6), 1, "m_admin_01", t, t, isoDate(-6), null, "task_p1_03"),
  taskInsert("task_p1_03_b", WS_ID, "proj_auralee_launch", "ws1_content", "촬영 및 소스 선별", null, "InProgress", "m_03", null, isoDate(-6), isoDate(1), 1, "m_admin_01", t, t, null, null, "task_p1_03"),
  taskInsert("task_p1_03_b1", WS_ID, "proj_auralee_launch", "ws1_content", "현장 촬영일", null, "Done", "m_03", null, isoDate(-5), isoDate(-5), 1, "m_admin_01", t, t, isoDate(-5), null, "task_p1_03_b"),
  taskInsert("task_p1_03_b2", WS_ID, "proj_auralee_launch", "ws1_content", "베스트 컷 선별 및 러프 편집", null, "InProgress", "m_02", null, isoDate(-3), isoDate(1), 1, "m_admin_01", t, t, null, null, "task_p1_03_b"),
  taskInsert("task_p1_03_c", WS_ID, "proj_auralee_launch", "ws1_content", "국문·영문 자막 추가", null, "ToDo", "m_02", null, null, isoDate(3), 1, "m_admin_01", t, t, null, null, "task_p1_03"),
  taskInsert("task_p1_04", WS_ID, "proj_auralee_launch", "ws1_content", "룩북 에디토리얼 카피 작성", "약 800자, 브랜드 톤. 레이아웃 전 리드 승인 필요.", "Review", "m_02", "m_admin_01", isoDate(-14), isoDate(-3), 2, "m_admin_01", t, t, null, null),
  taskInsert("task_p1_05", WS_ID, "proj_auralee_launch", "ws1_content", "24 SS 캠페인 파트너 UGC 사용 동의 확보", "콘텐츠 재사용을 위해 파트너 12곳에 서면 동의를 요청한다.", "Waiting", "m_04", null, isoDate(-12), isoDate(-5), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p1_06", WS_ID, "proj_auralee_launch", "ws1_distribution", "론칭 주간 유료 광고 집행 일정 수립", "Meta·TikTok. 집행 전 재무팀과 예산 확정.", "ToDo", "m_04", "m_admin_01", isoDate(0), isoDate(5), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p1_07", WS_ID, "proj_auralee_launch", "ws1_distribution", "국내 미디어 리스트에 보도자료 배포", "론칭 당일 오전 9시까지 엠바고. PR 대행사 참조.", "ToDo", "m_02", "m_admin_01", isoDate(2), isoDate(7), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p1_08", WS_ID, "proj_auralee_launch", "ws1_analytics", "론칭 링크 UTM 트래킹 설정", "표준 네이밍 규칙 사용: source / medium / campaign = ss25launch.", "InProgress", "m_04", "m_02", isoDate(-5), isoDate(1), 1, "m_02", t, t, null, null),
  taskInsert("task_p1_09", WS_ID, "proj_auralee_launch", "ws1_analytics", "24 SS 캠페인 성과 리포트 공유", "25 SS 예산 배분을 위한 회고 자료.", "Waiting", "m_04", "m_admin_01", isoDate(-21), isoDate(-7), 2, "m_admin_01", t, t, null, null),
  taskInsert("task_p2_01", WS_ID, "proj_cultural_collab", "ws2_partnerships", "협업 후보 아티스트 10팀 선정", "기준: 팬층 적합성, 무드 일치, 참여율 3% 이상.", "Done", "m_02", "m_admin_01", isoDate(-12), isoDate(-8), 2, "m_02", t, t, isoDate(-8), null),
  taskInsert("task_p2_02", WS_ID, "proj_cultural_collab", "ws2_partnerships", "아티스트 소속사 컨택", "초기 DM 및 협업 브리프 첨부 메일 발송.", "Waiting", "m_02", null, isoDate(-7), isoDate(5), 1, "m_02", t, t, null, null),
  taskInsert("task_p2_03", WS_ID, "proj_cultural_collab", "ws2_creative", "아티스트 공동 창작 브리프 작성", "창작 권리, 사용 범위, 승인 절차 포함.", "InProgress", "m_03", "m_admin_01", isoDate(-5), isoDate(4), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p2_04", WS_ID, "proj_cultural_collab", "ws2_creative", "영상 협업 무드보드 작성", "레퍼런스: 절제된 색감, 슬로우 시네마 무드.", "ToDo", "m_03", "m_02", isoDate(3), isoDate(12), 1, "m_02", t, t, null, null),
  taskInsert("task_p2_05", WS_ID, "proj_cultural_collab", "ws2_events", "서울 컬처 믹서 장소 리서치", "수용 인원 80~120명, 성수·북촌 등 아트 공간 선호.", "Inbox", null, null, null, isoDate(20), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p2_06", WS_ID, "proj_cultural_collab", "ws2_partnerships", "확정 파트너 2팀 계약 마무리", "법무 검토 및 서명 필요. 표준 협업 계약서 사용.", "Review", "m_02", "m_admin_01", isoDate(-10), isoDate(-3), 3, "m_admin_01", t, t, null, null),
  taskInsert("task_p3_01", WS_ID, "proj_brand_strategy", "ws3_research", "경쟁 브랜드 오디트 (5개 브랜드)", "국내 럭셔리·컨템포러리 브랜드 중심. 소셜 리스닝 활용.", "Done", "m_04", "m_admin_01", isoDate(-7), isoDate(-4), 1, "m_admin_01", t, t, isoDate(-4), null),
  taskInsert("task_p3_02", WS_ID, "proj_brand_strategy", "ws3_research", "소비자 설문 — 국내 18~35세 200명", "네이버 폼 사용. 브랜드 인식 프레임워크 기반 문항.", "InProgress", "m_04", "m_02", isoDate(-6), isoDate(1), 2, "m_admin_01", t, t, null, null),
  taskInsert("task_p3_03", WS_ID, "proj_brand_strategy", "ws3_messaging", "브랜드 포지셔닝 문구 초안 v1", "For / Who / That / Unlike 프레임워크. 후보 2~3개.", "InProgress", "m_admin_01", null, isoDate(-4), isoDate(2), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p3_04", WS_ID, "proj_brand_strategy", "ws3_messaging", "브랜드 보이스 용어 30개 정의", "톤: 절제되고 미니멀, 문화적. 국문·영문 병기.", "ToDo", "m_03", "m_admin_01", isoDate(1), isoDate(4), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p3_05", WS_ID, "proj_brand_strategy", "ws3_presentation", "발표 자료 뼈대 구성 (20장)", "메종 키츠네 브랜드 시스템 템플릿. 섹션 헤더·플레이스홀더 카피.", "Review", "m_03", "m_admin_01", isoDate(-3), isoDate(0), 2, "m_admin_01", t, t, null, null),
  taskInsert("task_p3_06", WS_ID, "proj_brand_strategy", "ws3_presentation", "경영진 리허설 — 30분 리뷰", "최종 보고 2일 전 진행.", "Inbox", "m_admin_01", null, null, isoDate(5), 1, "m_admin_01", t, t, null, null),
  taskInsert("task_p3_07", WS_ID, "proj_brand_strategy", "ws3_research", "상반기 캠페인 데이터 핵심 인사이트 정리", "전략 자료 3번 섹션에 반영. 상위 3~5개 발견 강조.", "Waiting", "m_04", "m_admin_01", isoDate(-9), isoDate(-4), 2, "m_admin_01", t, t, null, null),
  "",
  // Milestones are tasks (migration 0004). Seeding the legacy `milestone`
  // table here would strand them: on a fresh database 0004 has already run by
  // the time the seed lands, so nothing would ever move them across.
  "-- Milestones",
  milestoneInsert("ms_p1_01", "proj_auralee_launch", "크리에이티브 소재 확정", isoDate(3), 0),
  milestoneInsert("ms_p1_02", "proj_auralee_launch", "25 SS 론칭일", isoDate(14), 1),
  milestoneInsert("ms_p2_01", "proj_cultural_collab", "파트너 계약 완료", isoDate(7), 0),
  milestoneInsert("ms_p2_02", "proj_cultural_collab", "컬처 믹서 이벤트", isoDate(30), 1),
  milestoneInsert("ms_p3_01", "proj_brand_strategy", "발표 자료 초안 완성", isoDate(2), 0),
  milestoneInsert("ms_p3_02", "proj_brand_strategy", "경영진 발표", isoDate(7), 1),
];

/** A milestone: a task whose kind says it is a date the project turns on. */
function milestoneInsert(
  id: string,
  projectId: string,
  name: string,
  dueDate: string,
  order: number
): string {
  return `INSERT INTO task (id, workspace_id, project_id, workstream_id, parent_task_id, title, description, status, importance, kind, assignee_id, reviewer_id, start_date, due_date, sort_order, version, created_by, created_at, updated_at, completed_at, cancelled_at) VALUES (${esc(id)}, ${esc(WS_ID)}, ${esc(projectId)}, NULL, NULL, ${esc(name)}, NULL, 'ToDo', 'normal', 'milestone', NULL, NULL, NULL, ${esc(dueDate)}, ${100 + order}, 1, 'm_admin_01', ${esc(t)}, ${esc(t)}, NULL, NULL) ON CONFLICT (id) DO NOTHING;`;
}

function taskInsert(
  id: string,
  workspaceId: string,
  projectId: string | null,
  workstreamId: string | null,
  title: string,
  description: string | null,
  status: string,
  assigneeId: string | null,
  reviewerId: string | null,
  startDate: string | null,
  dueDate: string | null,
  version: number,
  createdBy: string,
  createdAt: string,
  updatedAt: string,
  completedAt: string | null,
  cancelledAt: string | null,
  parentTaskId: string | null = null
): string {
  return `INSERT INTO task (id, workspace_id, project_id, workstream_id, parent_task_id, title, description, status, assignee_id, reviewer_id, start_date, due_date, version, created_by, created_at, updated_at, completed_at, cancelled_at) VALUES (${esc(id)}, ${esc(workspaceId)}, ${esc(projectId)}, ${esc(workstreamId)}, ${esc(parentTaskId)}, ${esc(title)}, ${esc(description)}, ${esc(status)}, ${esc(assigneeId)}, ${esc(reviewerId)}, ${esc(startDate)}, ${esc(dueDate)}, ${version}, ${esc(createdBy)}, ${esc(createdAt)}, ${esc(updatedAt)}, ${esc(completedAt)}, ${esc(cancelledAt)}) ON CONFLICT (id) DO NOTHING;`;
}

console.log(lines.join("\n"));
console.error("[seed-db] Seed SQL generated. Pipe to: wrangler d1 execute DB --local --file=-");
